language: r

# Be strict when checking our package
warnings_are_errors: true
cran: http://cran.us.r-project.org

# System dependencies for HTTP calling
apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev
 - r-cran-rjava
